return {

    [4871329703] = {
        Name    = "Type Soul",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/14d17ae9ee94144cb99f7a8bb882861f.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/23257859e8c9ae8dc0af767c0def924b.lua",
    },

    [8524572339] = {
        Name    = "bridger: WESTERN",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/00f66c6113c62438df3ad3ba4ab54ddc.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/62fae3fc8ed63cf34669218569de1eb0.lua",
    },


    [5130394318] = {
        Name    = "Bizarre Lineage",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/8e596a14b226166df1768ba08d56d4b7.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/1d81a6853a3d06f84ff080a9df897512.lua",
    },

    [4658598196] = {
        Name    = "AOTR",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/5ca5aecc9b4650eea56cfcf9418fe87a.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/083df767880b4503a08252f478a1e8cf.lua",
    },

    [6760085372] = {
        Name    = "Jujutsu Zero",
        PaidUrl = nil,
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/18eb981418ced3ee300d434394f254fb.lua",
    },

    [9186719164] = {
        Name    = "Sailor Piece",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/60b92b9536dd001f847cf6dfa6baf96a.lua",
        FreeUrl = nil,
    },

    [578392296] = {
        Name    = "ABA",
        PaidUrl = "https://api.luarmor.net/files/v4/loaders/c9b0fca9ee7806da690cd40c77751691.lua",
        FreeUrl = "https://api.luarmor.net/files/v4/loaders/fb277df44e3bc5d7b727588f9302c1d5.lua",
    },

    [9271746647] = {
        Name    = "Baseplate",
        PaidUrl = "https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source",
        FreeUrl = "https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source",
    },

}
